### PR TITLE
Added Web Links plugin

### PR DESCRIPTION
**Pull request by hmueller01**
Added Web Links (com_weblinks) plugin. This addresses #1.
You can use the title or the alias of the Web Link. The alias might be more unique.

### CODE REVIEW

**Comment by gesellix** [comment]
Hi, thanks a lot for your efforts! Can you tell whether you've already tested it in a Joomla installation and if so, which version?

**Comment by hmueller01** [comment]
Hi, I tested it on Joomla 3.9/3.9.1 using PHP 7.0.30.

**Comment by hmueller01** [comment]
The only disadvantage of my approach is that the used Web Links are not counted, as I use the target URL directly. Maybe it might be better to use a link like `.../index.php?option=com_weblinks&task=weblink.go&id=19` instead. What do you think?

**Comment by gesellix** [comment]
> Web Links are not counted

ah, you're right, that might be surprising. Would you like to modify your PR accordingly?

**Comment by hmueller01** [comment]
Sorry, haven't seen your response earlier (missed the notification email).
I changed the link and now the hits are counted.

**Comment by hmueller01** [comment]
Just wondering, if you are willing to except this pull request ...
Works fine on my web site https://holger.euhm.de

**Comment by gesellix** [comment]
Sorry for the delay, I'm actually willing to merge this PR. Yet, making an official release (e.g. on the Joomla Extensions website) will happen a bit later.
Thanks for your patience!

**Comment by hmueller01** [comment]
Of course. No need to have this right now on official release. Thanks for merging my pull request.

**Pull request merged**
